name: Run Tests
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # Adjust to your project's .NET version

      - name: Install dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test
